### ISSUE TITLE
OSTrack export onnx model

### ISSUE THREAD

**Issue by CooolWindS** [l-sf/Track-trt#1]
Hello,

Thank you for providing such a comprehensive tool. However, due to version constraints and the need to customize my own OSTrack model, could you please share the code for exporting the ONNX model?

Thank you very much!

**Comment by l-sf** [comment]
The onnx export method has been uploaded, please look at [readme](https://github.com/l-sf/Track-trt/blob/main/ostrack/README.md). Thank you for your attention!
