### ISSUE TITLE
Get confident score 

### ISSUE THREAD

**Issue by vongocminh778** [l-sf/Track-trt#2]
Please help me get confident score from OSTrack, i can't find it.

**Comment by l-sf** [comment]
https://github.com/l-sf/Track-trt/blob/2db276e6c41d80b4b5f70c26a1cfc71c2862f8b4/ostrack/OSTrack.cpp#L87
The pointers to the model outputs(score, size, offset) are all here.
![image](https://github.com/l-sf/Track-trt/assets/78126612/aeb5bbe2-d876-4422-a686-467cb1e560cc)

**Comment by vongocminh778** [comment]
Thanks
