### ISSUE TITLE
trtexec command not found

### ISSUE THREAD

**Issue by arielkantorovich** [l-sf/Track-trt#4]
Hi,
Thank you for the great repo, I tried to run your work on my Jetson Nano, the jetson nano came with Cuda and tensort buildin' installation so immediately I try to extract tensorRT from your Onnx model I get this error:
`trtexec command not found`
I will be happy to any help or instructions from you on what I missing. 

In addition in the future you have some idea to update this repo and add Python code that is equivalent to your cpp code?

Update:
I succeed to solve this problem by: ` cp /usr/src/tensorrt/bin /usr/local/bin`

**Comment by l-sf** [comment]
Hi, thanks for your interest in my work.

Yes, you are right. A simpler way is to add the path of trtexec to the `$PATH` environment variable: 
`export PATH=$PATH:/usr/src/tensorrt/bin`

I'm sorry that I don't intend to update the Python code because deployment aims for high performance, and C++ is the preferred high-performance language.

Best wishes.

**Comment by arielkantorovich** [comment]
Thanks for your reply, I have one last question TensorRT path library that I need to change at CMakeList.txt, (jetson nano)  `/usr/src/tensorrt/bin` did I miss something?
There is another path file?

**Comment by l-sf** [comment]
Hi,

This `/usr/src/tensorrt/bin` path is just the path to the `trtexec` executable program, add 
`export PATH=$PATH:/usr/src/tensorrt/bin` to your `~/.bashrc`, then `source ~/.bashrc`,  you can run the `trtexec` command in any terminal.

For CMakeLists.txt, as Jetson Nano directly installed TensorRT, so you need to directly add the **header file path of tensorrt** to `include_directories` and adding **dynamic library path of tensorrt** to `link_directories`, such as:
![image](https://github.com/l-sf/Track-trt/assets/78126612/cadf220d-b5bb-4a27-bac2-4cc5295d3ef9)
In my Jetson Orin Nano, their path is like this, you need to check your device to ensure it is correct.

Finally, you need to modify the [computing power](https://github.com/l-sf/Track-trt/blob/2db276e6c41d80b4b5f70c26a1cfc71c2862f8b4/CMakeLists.txt#L50) of your device, please refer to the reference link. Jetson Nano is 53.

Please use the LightTrack model as the computational power of Jetson Nano is too low.

Best wishes.

**Comment by arielkantorovich** [comment]
Wow you the best thank you!
but I see in your CMake lists paths such 
`set(CMAKE_BUILD_RPAT "/home/lsf/Third_party....")` and `set(TENSORRT_DIR "/home/lsf/Third_party....")`
Do I need to change them? or this does not matter

**Comment by l-sf** [comment]
Both of these two lines 
`set(CMAKE_BUILD_RPAT "/home/lsf/Third_party....")` and `set(TENSORRT_DIR "/home/lsf/Third_party....")`
can be deleted without any impact, as my tensorrt was installed by a third party in home path.

And you can set the `CMAKE_BUILD_TYPE` from Debug to Release, which may make the program run faster.
![image](https://github.com/l-sf/Track-trt/assets/78126612/dca3e4b8-dcbc-4059-9db8-df7f5147e3f8)

**Comment by arielkantorovich** [comment]
When I compile I get this error `fatal error: boost/format.hpp: No such file or directory
`#include <boost/format.hpp>`
Update:
If I understand I need to install a boost on Jetson Nano?

**Comment by l-sf** [comment]
Boost is a system level library, as long as you install the C++ related compilation environment, it will generally be installed, and manual installation is not recommended. You can search for relevant blogs online.

**Comment by arielkantorovich** [comment]
Again thank you for your answers I succeeded in compailing when I ran the video example bug.avi I got inferred time: 393.85ms what I missing?

**Comment by l-sf** [comment]
Firstly, confirm that the generated trt engine is fp16 precision. If this is not wrong, then the Jetson Nano's computing power is too low! 

You can go to NVIDIA's official website to check the frequency and number of cores of Jetson Nano's CPU and GPU, which should be much lower than Jetson Orin Nano.

![image](https://github.com/l-sf/Track-trt/assets/78126612/e6bc0e96-58ae-4842-ad4a-ddfa8a0dd9a8)
