### ISSUE TITLE
trt_common support precesion int8 (question)

### ISSUE THREAD

**Issue by arielkantorovich** [l-sf/Track-trt#5]
Hi,
thank you for the great work, I tried your project on Jetson Nano, I got with fp16 latency of ~40m [sec], and I tried to improve the FPS using int8 precision.
I understand that I going to pay for this be low accuracy but I still want to try.
I run ./compile_engine.sh with flag --int8 succeed extract *.trt but for some reason I got high latency from fp16 what did I miss?

**Comment by l-sf** [comment]
The GPU on the old Jetson Nano and Jetson TX2 are both Pascal architecture and do not have hardware support for computing Int8. FP16 is the fastest.
