### ISSUE TITLE
Frame rate reduce when object track break(question)

### ISSUE THREAD

**Issue by arielkantorovich** [l-sf/Track-trt#8]
Hi,
I distinguished when the object occluded or out from frame the frame-rate reduce dramatically I will glad to get your feedback about this subject because I not understand why it happens.

**Comment by l-sf** [comment]
In general, when target tracking fails or the target exits the field of view, the target box tends to become larger. As the target box increases in size, the computational load during the preprocessing stage (using OpenCV) intensifies, leading to a decrease in processing speed. Therefore, the fundamental reason for the slowdown is the enlargement of the target box. Similarly, if the target being tracked is inherently large, the processing speed will also be reduced.

**Comment by arielkantorovich** [comment]
thank you for answering, there is something that I missing in your answer if I track object and in some frame the object out from frame and I got large bb which prep-reprocessing you mean? because I not update the template my template is in the original size. The only different I saw is drawing large BB so I not exactly understand where is the bottleneck in the process. 
Thank you again for great work !

**Comment by l-sf** [comment]
In the preprocessing stage of tracking, cropping and padding are crucial steps. The purpose of cropping the target area is to ensure that the target box maintains a consistent proportion within the cropped region. When the target box becomes larger, the number of pixels that need to be processed increases. Consequently, the computational load on OpenCV functions escalates, as they must now handle a greater volume of pixel data. This increase in computational complexity directly affects the processing speed, leading to a decrease in overall performance.
You can carefully read this [function](https://github.com/l-sf/Track-trt/blob/2db276e6c41d80b4b5f70c26a1cfc71c2862f8b4/lighttrack/LightTrack.cpp#L191) .
